model_dir: ${datetime:"checkpoints/wavenet"}
model:
  residual_layers: 30
  residual_channels: 128
  dilation_cycle_length: 10
data:
  data_dir: dataset
  batch_size: 32
  num_workers: 2
trainer:
  fp16: True
  learning_rate: 5e-4
  max_steps: 32_000
  log_every: 50
  save_every: 2000
  validate_every: 2000